---
- name: Fetch all devices
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get all devices from the API
      ansible.builtin.uri:
        url: "http://localhost:5000/devices"
        method: GET
        return_content: yes
      register: result

    - name: Display all devices
      debug:
        var: result.json

