---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts
  connection: ansible.builtin.ssh   # default connection type

  # these variables are used to build templates
  vars_files:
    - vars/planetexpress.yml

  tasks:
    - name: Configure spaceship registration
      ansible.builtin.template:
        src: templates/ship.cfg.j2    # name of the template on ansible controller
        dest: ~/ship.cfg              # name of the completed file to be placed on the target system

    - name: Configure mission orders
      ansible.builtin.template:
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: ~/{{ item.mission }}-mission-orders.txt" # name of the completed file to be placed on the target system
      vars:
          planet: "{{ item.planet }}"
      loop:   # each time through the loop, each dict (list entry) will be an "item"
          - {"mission": "primary", "planet": "luna park"}
          - {"mission": "secondary", "planet": "cineplex 14"}  ## This is the list we want to loop across

